### DISCUSSION TITLE
Enabling CodeQL on GitHub Enterprise Server

### DISCUSSION THREAD

**Discussion by giscus** [rajbos/rajbos.github.io#29] [Comments]
# Enabling CodeQL on GitHub Enterprise Server

Enabling CodeQL on GitHub Enterprise Server

https://devopsjournal.io/blog/2023/02/07/Enabling-codeql-on-GitHub-Enterprise-Server

**Comment by jessehouwing** [comment]
One of the tricks to get your tools cache primed is to run a workflow on a internet connected runner, zip up the tools cache in the final step and attach it as a build artefact, release or universal package. Then have another workflow or a custom setup-step that pulls the contents of that folder and extracts it to the runner at the start of the job.

**Reply by rajbos** [reply]
You can also then just cache it, but defining when to bust the cache can be a bit difficult. 

Keep in mind that both options will still incur data being downloaded, which can be an expensive operation (depending on your server/infrastructure/network setup)

**Reply by jessehouwing** [reply]
I did something like that for renovate recently. I query the version of renovate and cat that to a file. Then use that file to detect if I can restore the cache. Still 1 call to fetch the latest version, but works like a charm otherwise.

**Reply by jessehouwing** [reply]
```
    - name: Get renovate version
      shell: pwsh
      run: |
        npm show renovate version >> renovate-lock.txt

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: npm-cache-${{ hashFiles('renovate-lock.txt') }}
```

See: https://github.com/microsoft/azure-devops-extension-tasks/blob/e456e6b2a6d9b0f098b17c2bd7a2e31a23012322/.github/workflows/renovate.yml#L50-L55
